# Generated by Django 6.0.3 on 2026-03-26 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourM', '0041_enroll_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Size',
            field=models.PositiveIntegerField(default='1', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(11)]),
        ),
    ]
